Source/MovieRating/MovieRating.Web/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieRating.DataAccess.Models.DB;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Security.Claims;

namespace MovieRating.Web.Controllers
{
   [Authorize]
    public class GroupsController : Controller
    {
        private readonly MovieRatingContext _context;

        public GroupsController(MovieRatingContext context)
        {
            _context = context;
        }

        // GET: Groups
        public async Task<IActionResult> Index()
        {
            var currentUser = await GetCurrentUser();
            var UserGroups = _context.Usergroup.Where(ug => ug.UserId == currentUser.UserId);

            var PendingUserGroups = UserGroups.Where(ug => ug.Level == 0);
            var PendingGroups = _context.Group.Where(g => PendingUserGroups.Any(ug => ug.GroupId == g.GroupId));

            var MemberUserGroups = UserGroups.Where(ug => ug.Level == 1);
            var MemberGroups = _context.Group.Where(g => MemberUserGroups.Any(ug => ug.GroupId == g.GroupId));
            
            var OwnedUserGroups = UserGroups.Where(ug => ug.Level == 2);
            var OwnedGroups = _context.Group.Where(g => OwnedUserGroups.Any(ug => ug.GroupId == g.GroupId));

            return View(Tuple.Create<IEnumerable<Group>, IEnumerable<Group>, IEnumerable<Group>>(PendingGroups.ToList(), OwnedGroups.ToList(), MemberGroups.ToList()));
        }

        // GET: Groups/Create
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: Group/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description")] Group group)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await GetCurrentUser();

                _context.Update(group);
                await _context.SaveChangesAsync();

                var UserGroup = new Usergroup
                {
                    GroupId = group.GroupId,
                    UserId = currentUser.UserId,
                    Level = 2
                };
                _context.Update(UserGroup);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(group);
        }

        [HttpGet]
        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var currentUser = await GetCurrentUser();
            var UserGroup = _context.Usergroup.Where(u => u.GroupId == id).Where(u => u.UserId == currentUser.UserId).FirstOrDefault();

            if (UserGroup.Level == 2) // Only admin can leave
            {
                _context.Usergroup.Remove(UserGroup);

                var Members = _context.Usergroup.Where(u => u.GroupId == id);
                foreach (var Member in Members)
                {
                    _context.Remove(Member);
                }

                var Group = _context.Group.Where(g => g.GroupId == id).FirstOrDefault();
                _context.Remove(Group);

                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Groups/InviteIndex/5
        [HttpGet]
        public async Task<IActionResult> Invite(int id)
        {
            var currentUser = await GetCurrentUser();

            var UserGroup = _context.Usergroup.Where(ug => ug.UserId == currentUser.UserId && ug.GroupId == id).FirstOrDefault();
            if (UserGroup == null) // Not the member of such a group
            {
                return RedirectToAction(nameof(Index));
            }

            var Friendships = _context.Friendship.Where(f => f.UserId == currentUser.UserId || f.FriendId == currentUser.UserId);
            var Friends = _context.User.Where(u => u.UserId != currentUser.UserId && Friendships.Any(f => f.UserId == u.UserId || f.FriendId == u.UserId));

            var GroupUsers = _context.Usergroup.Where(ug => ug.GroupId == id);

            var Group = _context.Group.Where(g => g.GroupId == id).FirstOrDefault();
            ViewData["Group"] = Group;

            return View(Friends.Where(u => !GroupUsers.Any(ug => ug.UserId == u.UserId)).ToList());
        }

        // GET: Groups/Invite/5
        [HttpPost]
        public async Task<IActionResult> Invite(int GroupId, int UserId)
        {
            var currentUser = await GetCurrentUser();

            var UserGroup = _context.Usergroup.Where(ug => ug.UserId == currentUser.UserId && ug.GroupId == GroupId).FirstOrDefault();
            if (UserGroup == null) // Not the member of such a group
            {
                return NotFound();
            }

            var Friend = _context.Friendship
                .Where(f => (f.UserId == currentUser.UserId && f.FriendId == UserId)
                            || (f.FriendId == currentUser.UserId && f.UserId == UserId)).FirstOrDefault();
            if (Friend == null) // Not friends
            {
                return NotFound();
            }

            var FriendUserGroup = _context.Usergroup.Where(ug => ug.UserId == UserId && ug.GroupId == GroupId).FirstOrDefault();
            if (FriendUserGroup != null) // Already member of such group
            {
                return NotFound();
            }

            _context.Usergroup.Add(new Usergroup()
            {
                GroupId = GroupId,
                UserId = UserId,
                Level = 0
            });
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Invite), new { id = GroupId });
        }

        // GET: Groups/AcceptInvitation/5
        [HttpGet]
        public async Task<IActionResult> AcceptInvitation(int id)
        {
            var currentUser = await GetCurrentUser();
            
            var group = await _context.Group.Include(w => w.Usergroup).SingleOrDefaultAsync(g => g.GroupId == id);
            if (group == null)
            {
                return NotFound();
            }

            var userGroup = group.Usergroup.FirstOrDefault(ug => ug.UserId == currentUser.UserId && ug.Level == 0);
            if (userGroup == null)
            {
                return NotFound();
            }

            userGroup.Level = 1;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: Groups/ViewRaingts/Index
        [HttpGet]
        public async Task<IActionResult> ViewRatings(int id)
        {
            var currentUser = await GetCurrentUser();

            var UserGroup = _context.Usergroup.Where(ug => ug.UserId == currentUser.UserId && ug.GroupId == id).FirstOrDefault();
            if (UserGroup == null) // Not the member of such a group
            {
                return RedirectToAction(nameof(Index));
            }

            var UserGroups = _context.Usergroup.Where(ug => ug.GroupId == id && ug.Level != 0);
            var Ratings = _context.Rating.Where(r => r.UserId != currentUser.UserId && UserGroups.Any(ug => ug.UserId == r.UserId));
            var UserRatings = _context.Rating.Where(r => r.UserId == currentUser.UserId);
            var Movies = _context.Movie.Where(m => Ratings.Any(r => r.MovieId == m.MovieId) && !UserRatings.Any(r => r.MovieId == m.MovieId));

            foreach (var movie in Movies)
            {
                movie.Rating = Ratings.Where(r => r.MovieId == movie.MovieId).ToList();
            }

            return View(Movies.OrderBy(m => m.Rating.Average(r => r.Score)).Take(15).ToList());
        }

        // GET: Groups/Leave/5
        [HttpGet]
        public async Task<IActionResult> Leave(int id)
        {
            var currentUser = await GetCurrentUser();
            var UserGroup = _context.Usergroup.Where(u => u.GroupId == id).Where(u => u.UserId == currentUser.UserId).FirstOrDefault();

            if (UserGroup.Level == 1) // Only member can leave
            {
                _context.Usergroup.Remove(UserGroup);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool GroupExists(int id)
        {
            return _context.Group.Any(e => e.GroupId == id);
        }

        private async Task<User> GetCurrentUser()
        {
            User currentUser = null;
            foreach (Claim claim in User.Claims.ToList())
            {
                if (claim.Type == ClaimTypes.Name)
                {
                    currentUser = await _context.User.FirstOrDefaultAsync(r => r.Username.Equals(claim.Value));
                }
            }
            return currentUser ?? new User();
        }
    }
}

Source/MovieRating/MovieRating.Web/Controllers/TMDBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using TMDbLib.Client;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Authorization;
using MovieRating.DataAccess.Models.DB;
using TMDbLib.Objects.Movies;

namespace MovieRating.Web.Controllers
{
    [Authorize]
    public class TMDBController : Controller
    {
        private readonly APIConfiguration _apiconfig;
        private MovieRatingContext _context;
        private TMDbClient _client;
        private Boolean _inited;

        public TMDBController(MovieRatingContext context, IOptions<APIConfiguration> apiconfig)
        {
            _apiconfig = apiconfig.Value;
            _context = context;
            try
            {
                _client = new TMDbClient(_apiconfig.Key);
                _inited = true;
            }
            catch
            {
                _inited = false;
            }
        }

        // GET: TMDB/Index
        public async Task<IActionResult> Index()
        {
            var Movies = await _client.GetMoviePopularListAsync();

            return View("Search", Movies.Results);
        }

        // GET: TMDB/Search/keywords
        public async Task<IActionResult> Search(String keywords)
        {
            var Movies = await _client.SearchMovieAsync(keywords);

            ViewData["keywords"] = keywords;

            return View(Movies.Results);
        }

        [HttpGet]
        // GET : TMDB/Details/id
        public async Task<IActionResult> Details(int id)
        {
            var Movie = await _client.GetMovieAsync(id, MovieMethods.Credits);

            return View(Movie);
        }

        // POST : TMDB/Rate/id
        [HttpPost]
        public IActionResult Rate(TMDbLib.Objects.Movies.Movie model)
        {
            var savedMovie = GetMovieIfNotExist(model);

            return RedirectToAction("Rate", "Movies", new { id = savedMovie.MovieId });
        }

        // POST : TMDB/AddList/id
        [HttpPost]
        public IActionResult AddList(TMDbLib.Objects.Movies.Movie model)
        {

            var savedMovie = GetMovieIfNotExist(model);

            return RedirectToAction("SelectLists", "MovieLists", new { movieId = savedMovie.MovieId });
        }

        /// <summary>
        /// Insert the movie to the database if it is not exist
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        private DataAccess.Models.DB.Movie GetMovieIfNotExist(TMDbLib.Objects.Movies.Movie model)
        {
            var savedMovie = _context.Movie.FirstOrDefault(m => m.MovieApiId == model.Id);

            if (savedMovie == null)
            {
                savedMovie = new DataAccess.Models.DB.Movie
                {
                    ImdbId = model.ImdbId,
                    Name = model.Title,
                    Year = (short)model.ReleaseDate.Value.Year,
                    MovieApiId = model.Id,
                    MovieTypeId = 1
                };

                _context.Add(savedMovie);
                _context.SaveChanges();
            }

            return savedMovie;
        }
    }
}

Source/MovieRating/MovieRating.Web/Views/Groups/Create.cshtml
@model MovieRating.DataAccess.Models.DB.Group

@{
    ViewData["Title"] = "Create";
}

<form asp-action="Create" method="post" class="form-signin">
    <input type="hidden" name="requestpath" id="requestpath" value="@ViewBag.RequestPath" />

    <h2 class="form-signin-heading">Please fill out these</h2>

    <label for="username" class="sr-only">Username</label>
    <input type="text" asp-for="Name" class="form-control" placeholder="Group name" required autofocus>

    <label for="password" class="sr-only">Password</label>
    <input type="text" asp-for="Description" class="form-control" placeholder="Description" required>

    <div asp-validation-summary="All" class="text-danger"></div>

    <button class="btn btn-lg btn-primary btn-block" type="submit">
        Create
    </button>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Source/MovieRating/MovieRating.Web/Views/Groups/Delete.cshtml
@model MovieRating.DataAccess.Models.DB.Group

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GroupId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GroupId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Usergroup)
        </dt>
        <dd>
            <div class="form-group">
                <table>
                    <th>UserName</th>
                    <th>InGroup</th>
                    <th>Level</th>
                    <th>JoinedDate</th>
                    @foreach (var user in ViewData["UserNames"] as List<MovieRating.DataAccess.Models.DB.User>)
                    {
                        <tr>
                            <td>@Html.DisplayFor(model => user.Username)</td>
                            <td>
                                @{
                                    var inDb = Model.Usergroup.Where(u => u.UserId == user.UserId).Where(w => w.GroupId == Model.GroupId).Count() == 1 ? "checked=\"true\"" : "";
                                    <input type="checkbox" @inDb id="@Html.DisplayFor(model => user.Username)-InGroup" name="@Html.DisplayFor(model => user.UserId)-InGroup" readonly/>
                                }
                            </td>
                            <td>
                                @{
                                    var inDbLeveln = Model.Usergroup.Where(u => u.UserId == user.UserId).Where(w => w.GroupId == Model.GroupId).FirstOrDefault();
                                    var inDbLevel = inDbLeveln == null ? "" : "value =" + @inDbLeveln.Level;
                                    <input type="number" id="@Html.DisplayFor(model => user.Username)-Level" name="@Html.DisplayFor(model => user.UserId)-Level" @inDbLevel min="1" max="2" readonly/>
                                }
                            </td>
                            <td>
                                @{
                                    var inDbJDaten = Model.Usergroup.Where(u => u.UserId == user.UserId).Where(w => w.GroupId == Model.GroupId).FirstOrDefault();
                                    var inDbJDate = inDbJDaten == null ? "" : "value =" + @Convert.ToDateTime(inDbJDaten.JoinedDate.Value).ToString("yyyy.MM.dd.-hh:mm:ss");
                                    <input type="datetime" id="@Html.DisplayFor(model => user.Username)-Level" name="@Html.DisplayFor(model => user.UserId)-Date" @inDbJDate readonly placeholder="automatically updated" />
                                }
                            </td>
                        </tr>
                    }
                </table>
                <input asp-for="Usergroup" class="form-control" type="hidden" />
                <span asp-validation-for="Usergroup" class="text-danger"></span>
            </div>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="GroupId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Source/MovieRating/MovieRating.Web/Views/Groups/Edit.cshtml
@model MovieRating.DataAccess.Models.DB.Group

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Group</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GroupId" />
            <div class="form-group">
                <label asp-for="GroupId" class="control-label"></label>
                <input readonly asp-for="GroupId" class="form-control" />
                <span asp-validation-for="GroupId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input required asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Usergroup" class="control-label"></label>
                <table>
                    <th>UserName</th>
                    <th>InGroup</th>
                    <th>Level</th>
                    <th>JoinedDate</th>
                    @foreach (var user in ViewData["UserNames"] as List<MovieRating.DataAccess.Models.DB.User>)
                    {
                        <tr>
                            <td>@Html.DisplayFor(model => user.Username)</td>
                            <td>
                                @{
                                    var inDb = Model.Usergroup.Where(u => u.UserId == user.UserId).Where(w => w.GroupId == Model.GroupId).Count() == 1 ? "checked=\"true\"" : "";
                                    <input type ="checkbox" @inDb id="@Html.DisplayFor(model => user.Username)-InGroup" name="@Html.DisplayFor(model => user.UserId)-InGroup"/>  
                                }
                            </td>
                            <td>
                                @{
                                    var inDbLeveln = Model.Usergroup.Where(u => u.UserId == user.UserId).Where(w => w.GroupId == Model.GroupId).FirstOrDefault();
                                    var inDbLevel = inDbLeveln == null ? "" : "value =" +@inDbLeveln.Level;
                                    <input type="number" id="@Html.DisplayFor(model => user.Username)-Level" name="@Html.DisplayFor(model => user.UserId)-Level" @inDbLevel min="1" max="2" />
                                }
                            </td>
                            <td>
                                @{
                                    var inDbJDaten = Model.Usergroup.Where(u => u.UserId == user.UserId).Where(w => w.GroupId == Model.GroupId).FirstOrDefault();
                                    var inDbJDate = "";
                                    if (inDbJDaten != null && DateTime.MaxValue.Subtract(inDbJDaten.JoinedDate.Value).Days < 1)
                                    {
                                        inDbJDate = "Invited by a group member";
                                    }
                                    else if (inDbJDaten != null)
                                    {
                                        inDbJDate = @Convert.ToDateTime(inDbJDaten.JoinedDate.Value).ToString("yyyy.MM.dd.-hh:mm:ss");
                                    }

                                    var inDbJDateStr = inDbJDaten == null ? "" : "value =" + inDbJDate;
                                    <input type="datetime" id="@Html.DisplayFor(model => user.Username)-Level" name="@Html.DisplayFor(model => user.UserId)-Date" @inDbJDateStr readonly placeholder="automatically updated" />
                                }
                            </td>
                        </tr>
                    }
                </table>
                <input asp-for="Usergroup" class="form-control" type="hidden"/>
                <span asp-validation-for="Usergroup" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Source/MovieRating/MovieRating.Web/Views/Groups/Index.cshtml
@model Tuple<IEnumerable<MovieRating.DataAccess.Models.DB.Group>, IEnumerable<MovieRating.DataAccess.Models.DB.Group>, IEnumerable<MovieRating.DataAccess.Models.DB.Group>>

@{
    ViewData["Title"] = "Index";
    var currentUser = ViewData["CurrentUser"] as MovieRating.DataAccess.Models.DB.User;
}

<div class="container" style="width:600px">
    <div style="width:470px;float:left">
        <h2>Your groups</h2>
    </div>
    <div style="width:100px;float:right;margin-top:20px">
        <a asp-action="Create" class="btn btn-default btn-primary">Create New</a>
    </div>
    <div style="clear:both"></div>

    <hr />
    <h3>Pending invitations</h3>
    <hr />

    @if (Model.Item1.Count() == 0)
    {
        <div>
            None right now.
        </div>
    }

    <ul class="list-group">
        @foreach (var item in Model.Item1)
        {
            <li class="list-group-item" style="vertical-align:middle;line-height:35px">
                <div style="float:left">
                    @(item.Name)
                </div>
                <div style="float:right">
                    <a asp-action="AcceptInvitation" asp-route-id="@item.GroupId" class="btn btn-default btn-warning">Accept invitation</a>
                </div>
                <div style="clear:both"></div>
            </li>
        }
    </ul>

    <hr />
    <h3>Owned groups</h3>
    <hr />

    @if (Model.Item2.Count() == 0)
    {
        <div>
            You do not own any groups. Create one now!
        </div>
    }

    <ul class="list-group">
        @foreach (var item in Model.Item2)
        {
            <li class="list-group-item" style="vertical-align:middle;line-height:35px">
                <div style="float:left">
                    @(item.Name)
                </div>
                <div style="float:right">
                    <a asp-action="Invite" asp-route-id="@item.GroupId" class="btn btn-default btn-primary">Invite friends</a>
                    <a asp-action="ViewRatings" asp-route-id="@item.GroupId" class="btn btn-default btn-warning">List movies</a>
                    <a asp-action="Delete" asp-route-id="@item.GroupId" class="btn btn-default btn-danger">Delete</a>
                </div>
                <div style="clear:both"></div>
            </li>
        }
    </ul>

    <hr />
    <h3>Joined groups</h3>
    <hr />

    @if (Model.Item3.Count() == 0)
    {
        <div>
            You are not a member of any group. Asks your friends to invite you!
        </div>
    }

    <ul class="list-group">
        @foreach (var item in Model.Item3)
        {
            <li class="list-group-item" style="vertical-align:middle;line-height:35px">
                <div style="float:left">
                    @(item.Name)
                </div>
                <div style="float:right">
                    <a asp-action="Invite" asp-route-id="@item.GroupId" class="btn btn-default btn-primary">Invite friends</a>
                    <a asp-action="ViewRatings" asp-route-id="@item.GroupId" class="btn btn-default btn-warning">List movies</a>
                    <a asp-action="Leave" asp-route-id="@item.GroupId" class="btn btn-default btn-danger">Leave</a>
                </div>
                <div style="clear:both"></div>
            </li>
        }
    </ul>
</div>

Source/MovieRating/MovieRating.Web/Views/Groups/Invite.cshtml
@model IEnumerable<MovieRating.DataAccess.Models.DB.User>

@{
    ViewData["Title"] = "Invite";
    var group = @ViewData["Group"] as MovieRating.DataAccess.Models.DB.Group;
}

<div class="container" style="width:600px">
    <div>
        <h2>Invite to @group.Name</h2>
    </div>

    <hr />

    @if (Model.Count() == 0)
    {
        <div>
            Looks like all your friends are in the group!
        </div>
    }

    <ul class="list-group">
        @foreach (var item in Model)
        {
                <li class="list-group-item" style="vertical-align:middle;line-height:35px">
                    <div style="float:left">
                        @(item.Name) (@(item.Username))
                    </div>
                    <div style="float:right">
                        <form asp-action="Invite">
                            <input type="hidden" name="GroupId" value="@(group.GroupId)" />
                            <input type="hidden" name="UserId" value="@(item.UserId)" />
                            <button class="btn btn-primary btn-default" type="submit">
                                Invite
                            </button>
                        </form>
                    </div>
                    <div style="clear:both"></div>
                </li>
        }
    </ul>
</div>

Source/MovieRating/MovieRating.Web/Views/Groups/Leave.cshtml
@model IEnumerable<MovieRating.DataAccess.Models.DB.Movie>

@{
    ViewData["Title"] = "Leave";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var group = @ViewData["Group"] as MovieRating.DataAccess.Models.DB.Group;
}
<h2>Are you sure you want to leave @group.Name ?</h2>

<form asp-action="Leave">
    <input type="submit" value="Leave" class="btn btn-default" /> |
    <a asp-action="Index">Back to Groups</a>
</form>

Source/MovieRating/MovieRating.Web/Views/Groups/ViewRatings.cshtml
@model IEnumerable<MovieRating.DataAccess.Models.DB.Movie>

@{
    ViewData["Title"] = "Ratings";
}

<div class="container" style="width:600px">
    <h2>Find what others like in the group</h2>

    <hr />

    <ul class="list-group">
        @foreach (var item in Model)
        {
            <li class="list-group-item" style="vertical-align:middle;line-height:35px">
                <div style="float:left">
                    <span class="badge" style="width:40px">
                        @item.Rating.DefaultIfEmpty(new MovieRating.DataAccess.Models.DB.Rating { Score = 0 }).Average(r => r.Score)
                    </span>
                    @Html.DisplayFor(modelItem => item.Name)
                </div>
                <div style="float:right">
                    <a asp-controller="TMDB" asp-action="Details" asp-route-id="@item.MovieApiId" class="btn btn-default btn-primary">Details</a>
                    <a asp-controller="Movies" asp-action="Details" asp-route-id="@item.MovieId" class="btn btn-default btn-warning">Ratings</a>
                    <a asp-controller="Movies" asp-action="AddToList" asp-route-id="@item.MovieId" class="btn btn-default btn-info">Add to list</a>
                </div>
                <div style="clear:both"></div>
            </li>
        }
    </ul>
</div>