Source/MovieRating/MovieRating.Web/Controllers/MovieListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieRating.DataAccess.Models.DB;
using Microsoft.AspNetCore.Authorization;

namespace MovieRating.DataAccess.Controllers
{
    [Authorize]
    public class MovieListsController : Controller
    {
        private readonly MovieRatingContext _context;

        public MovieListsController(MovieRatingContext context)
        {
            _context = context;
        }


        // GET: MovieLists
        public async Task<IActionResult> Index()
        {
            return View(_context.Userlist.Where(u => u.UserId == GetUserId()).ToList());
        }

        public IActionResult Create()
        {
            ViewData["UserlistId"] = new SelectList(_context.Userlist, "UserlistId", "Name", "Public");
            return View();
        }

        // POST: Group/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserlistId,Name")] Userlist list, string Visibility)
        {
            list.Public = (Visibility == "Public");

            var isListNameInUse = _context.Userlist.Any(l => l.UserId == GetUserId() && l.Name == list.Name);
            if (isListNameInUse)
            {
                ModelState.AddModelError("Name", "The list name must be unique.");
            }
            
            if (ModelState.IsValid)
            {
                list.UserId = GetUserId();
                _context.Add(list);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(list);
        }

        public IActionResult SelectLists(int movieId)
        {
            ViewData["MovieId"] = movieId;
            return View(_context.Userlist.Where(u => u.UserId == GetUserId()).ToList());
        }


        public async Task<IActionResult> SaveSelectedLists(int listId, int movieId)
        {
            if (ModelState.IsValid)
            {
                if (!CheckUser(listId))
                {
                    return RedirectToAction(nameof(Index));
                }
                if (!_context.MovieList.Where(m => m.MovieId == movieId && m.UserlistId == listId).Any())
                {
                    MovieList ml2 = new MovieList();
                    ml2.MovieId = movieId;
                    ml2.UserlistId = listId;
                    _context.Add(ml2);

                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", "Movies");
                }

            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!CheckUser((int)id))
            {
                return RedirectToAction(nameof(Index));
            }
            var list = await _context.Userlist.SingleOrDefaultAsync(m => m.UserlistId == id);
            List<MovieList> movieList = _context.MovieList.Where(m => m.UserlistId == id).ToList();
            foreach (MovieList ml in movieList)
            {
                _context.MovieList.Remove(ml);
            }

            _context.Userlist.Remove(list);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? listId, int? userId)
        {
            ViewData["CurrentUser"] = "";
            if (listId == null)
            {
                return NotFound();
            }
            if (!CheckUser((int)listId) && !IsFriendUser((int)listId))
            {
                return RedirectToAction(nameof(Index));
            }
            if (userId != null && GetUserId() != _context.Userlist.First(u => u.UserlistId == listId).UserId)
            {
                ViewData["CurrentUser"] = "other";
            }
            var list = await _context.Userlist.SingleOrDefaultAsync(m => m.UserlistId == listId);
            ViewData["ListName"] = _context.Userlist.Find(listId).Name;
            ViewData["ListId"] = listId;

            List<MovieList> movieLists = _context.MovieList.Include(m => m.Movie).Where(m => m.Userlist.UserlistId == listId).ToList();
            return View(movieLists);
        }

        public async Task<IActionResult> Remove(int? listId, int? movieId)
        {
            if (listId == null || movieId == null)
            {
                return NotFound();
            }
            if (!CheckUser((int)listId))
            {
                return RedirectToAction(nameof(Index));
            }
            var movie = await _context.MovieList
                            .SingleOrDefaultAsync(m => m.UserlistId == listId && m.ListElementId == movieId);
            _context.MovieList.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { listId = listId });
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (!CheckUser((int)id))
            {
                return RedirectToAction(nameof(Index));
            }
            var list = await _context.Userlist.SingleOrDefaultAsync(m => m.UserlistId == id);
            if (list == null)
            {
                return NotFound();
            }

            ViewData["UserlistId"] = new SelectList(_context.Userlist, "UserlistId", "Name", "Public");
            return View(list);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("UserlistId,Name")] Userlist list, string Visibility)
        {
            list.Public = (Visibility == "Public");
            if (ModelState.IsValid)
            {
                try
                {
                    list.UserId = GetUserId();

                    _context.Update(list);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserlstId"] = new SelectList(_context.MovieType, "UserlistId", "Name", "Public");
            return View(list);
        }

        private int GetUserId()
        {
            String userName = this.User.Identity.Name;
            int userId = _context.User.ToList().Find(r => r.Username.Equals(userName)).UserId;
            return userId;
        }

        private bool CheckUser(int id)
        {
            int userId = GetUserId();
            return _context.Userlist.Include(u => u.User).Any(u => u.UserlistId == id && u.UserId == userId);
        }

        private bool IsFriendUser(int id)
        {
            int userId = GetUserId();
            List<Friendship> friends = _context.Friendship.Include(f => f.FriendUser)
                                            .Include(f => f.User).Where(f => (f.UserId == userId || f.FriendId == userId) && f.Status == 1).ToList();

            foreach (Friendship friend in friends)
            {
                if (_context.Userlist.Any(u => (u.UserId == friend.FriendId || u.UserId == friend.UserId) && u.UserlistId == id && u.Public))
                {
                    return true;
                }
            }
            return false;
        }

    }
}

Source/MovieRating/MovieRating.Web/Controllers/ProfilesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieRating.DataAccess.Models.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authentication;

namespace MovieRating.Web.Controllers
{
    [Authorize]
    public class ProfilesController : Controller
    {
        private readonly MovieRatingContext _context;

        public ProfilesController(MovieRatingContext context)
        {
            _context = context;
        }

        // GET: Profiles
        public async Task<ActionResult> Index()
        {
            var currentUser = await GetCurrentUser();
            ViewData["currentUser"] = currentUser;
            return View(currentUser);
        }

        // GET: Profiles/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentUser = await GetCurrentUser();
            ViewData["currentUser"] = currentUser;

            var areFriends = _context.Friendship.FirstOrDefault(f => 
                (f.UserId == currentUser.UserId && f.FriendId == id && f.Status == 1) ||
                (f.UserId == id && f.FriendId == currentUser.UserId && f.Status == 1)) != null;

            if (currentUser.UserId == id || !areFriends)
            {
                return RedirectToAction(nameof(Index));
            }

            var friendUser = await _context.User.Include(f => f.Userlist).FirstOrDefaultAsync(u => u.UserId == id);

            return View(nameof(Index), friendUser);
        }

        // GET: Profiles/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.Include(u => u.Usergroup).FirstOrDefaultAsync(u => u.UserId == id);

            if ((await GetCurrentUser()).UserId != id)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(user);
        }

        // POST: Profiles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int? id, [Bind("Username,Name,Email")] User user)
        {
            if (id == null || (await GetCurrentUser()).UserId != id)
            {
                return NotFound();
            }

            try
            {
                var userToModify = await _context.User.FirstOrDefaultAsync(u => u.UserId == id);

                if (user.Username != userToModify.Username && _context.User.Any(u => u.Username == user.Username))
                {
                    ModelState.AddModelError("UserName", "The username is already in use.");
                }

                if (String.IsNullOrWhiteSpace(user.Username))
                {
                    ModelState.AddModelError("UserName", "The username must not be empty.");
                }

                if (ModelState.IsValid)
                {
                    userToModify.Username = user.Username;
                    userToModify.Name = user.Name;
                    userToModify.Email = user.Email;

                    await _context.SaveChangesAsync();

                    if (userToModify.Username.Equals(user.Username))
                    {
                        await HttpContext.SignOutAsync(scheme: "MovieDatabase");
                        await SignInAsync(userToModify.Username);
                    }

                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        private async Task SignInAsync(string username)
        {
            // create claims
            List<Claim> claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, username),
            };

            // create identity
            ClaimsIdentity identity = new ClaimsIdentity(claims, "cookie");

            // create principal
            ClaimsPrincipal principal = new ClaimsPrincipal(identity);

            // sign-in
            await HttpContext.SignInAsync(
                    scheme: "MovieDatabase",
                    principal: principal);
        }

        virtual protected async Task<User> GetCurrentUser()
        {
            User currentUser = null;
            foreach (Claim claim in User.Claims.ToList())
            {
                if (claim.Type == ClaimTypes.Name)
                {
                    currentUser = await _context.User.Include(u => u.Userlist).FirstOrDefaultAsync(u => u.Username.Equals(claim.Value));
                }
            }
            return currentUser ?? new User();
        }
    }
}

Source/MovieRating/MovieRating.Web/Views/Profiles/Edit.cshtml
@model MovieRating.DataAccess.Models.DB.User

@{
    ViewData["Title"] = "Edit profile";
}

<div class="container" style="width:600px">
    <form asp-action="Edit">
        <div style="width:470px;float:left">
            <h2>Edit profile</h2>
        </div>
        <div style="width:100px;float:right;margin-top:20px">
            <input type="submit" value="Save profile" class="btn btn-default" />
        </div>
        <div style="clear:both"></div>

        <hr />

        <input type="hidden" asp-for="UserId" />

        <ul class="list-group">
            <li class="list-group-item" style="vertical-align:middle;line-height:35px">
                <div style="float:left">
                    Username
                </div>
                <div style="float:right">
                    <input asp-for="Username" class="form-control" />
                </div>
                <div style="clear:both"></div>
            </li>
            <li class="list-group-item" style="vertical-align:middle;line-height:35px">
                <div style="float:left">
                    Email
                </div>
                <div style="float:right">
                    <input asp-for="Email" class="form-control" />
                </div>
                <div style="clear:both"></div>
            </li>
            <li class="list-group-item" style="vertical-align:middle;line-height:35px">
                <div style="float:left">
                    Name
                </div>
                <div style="float:right">
                    <input asp-for="Name" class="form-control" />
                </div>
                <div style="clear:both"></div>
            </li>
            <li class="list-group-item" style="vertical-align:middle;line-height:35px">
                <div style="float:left">
                    Joined
                </div>
                <div style="float:right">
                    @Html.DisplayFor(model => model.JoinedDate)
                </div>
                <div style="clear:both"></div>
            </li>
        </ul>
    </form>
    <div asp-validation-summary="All" class="text-danger"></div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Source/MovieRating/MovieRating.Web/Views/Profiles/Index.cshtml
@model MovieRating.DataAccess.Models.DB.User

@{
    ViewData["Title"] = "User profile";
}

<div class="container" style="width:600px">

    <div style="width:470px;float:left">
        @if ((ViewData["currentUser"] as MovieRating.DataAccess.Models.DB.User).UserId == Model.UserId)
        {
            <h2>Your profile</h2>
        }
        else
        {
            <h2>@(Model.Username)'s profile</h2>
        }
    </div>
    @if ((ViewData["currentUser"] as MovieRating.DataAccess.Models.DB.User).UserId == Model.UserId)
    {
        <div style="width:100px;float:right;margin-top:20px">
            <a asp-action="Edit" asp-route-id="@Model.UserId" class="btn btn-default btn-primary">Edit profile</a>
        </div>
    }
    <div style="clear:both"></div>

    <hr />

    <ul class="list-group">
        <li class="list-group-item" style="vertical-align:middle;line-height:35px">
            <div style="float:left">
                Username
            </div>
            <div style="float:right">
                @Html.DisplayFor(model => model.Username)
            </div>
            <div style="clear:both"></div>
        </li>
        <li class="list-group-item" style="vertical-align:middle;line-height:35px">
            <div style="float:left">
                Email
            </div>
            <div style="float:right">
                @Html.DisplayFor(model => model.Email)
            </div>
            <div style="clear:both"></div>
        </li>
        <li class="list-group-item" style="vertical-align:middle;line-height:35px">
            <div style="float:left">
                Name
            </div>
            <div style="float:right">
                @Html.DisplayFor(model => model.Name)
            </div>
            <div style="clear:both"></div>
        </li>
        <li class="list-group-item" style="vertical-align:middle;line-height:35px">
            <div style="float:left">
                Joined
            </div>
            <div style="float:right">
                @Html.DisplayFor(model => model.JoinedDate)
            </div>
            <div style="clear:both"></div>
        </li>
    </ul>

    <hr />
    @if ((ViewData["currentUser"] as MovieRating.DataAccess.Models.DB.User).UserId == Model.UserId)
    {
        <h2>Your lists</h2>
    }
    else
    {
        <h2>@(Model.Username)'s lists</h2>
    }

    <hr />

    @if (Model.Userlist.Where(u => u.Public || ((ViewData["currentUser"] as MovieRating.DataAccess.Models.DB.User).UserId == Model.UserId)).Count() == 0)
    {
        <div style="float:left">
            None so far.
        </div>
        <div style="clear:both"></div>
    }

    <ul class="list-group">
        @foreach (var item in Model.Userlist.Where(u => u.Public || ((ViewData["currentUser"] as MovieRating.DataAccess.Models.DB.User).UserId == Model.UserId)))
        {
            <li class="list-group-item" style="vertical-align:middle;line-height:35px">
                <div style="float:left">
                    @Html.DisplayFor(modelItem => item.Name)
                </div>
                <div style="float:right">
                    @Html.ActionLink("Details", "Details", "MovieLists", new { listId = item.UserlistId, userId = (ViewData["currentUser"] as MovieRating.DataAccess.Models.DB.User).UserId }, new { @class = "btn btn-warning btn-default" })
                </div>
                <div style="clear:both"></div>
            </li>
        }
    </ul>
</div>