Source/MovieRating/MovieRating.Web/Controllers/SecurityController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authentication;
using System;
using MovieRating.Web.Models;
using MovieRating.DataAccess.Models.DB;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;
using System.Text;
using System.Linq;
using Microsoft.AspNetCore.Authorization;

namespace MovieRating.Web.Controllers
{
    public class SecurityController : Controller
    {
        public static string GenerateSHA256String(string inputString)
        {
            SHA256 sha256 = SHA256Managed.Create();
            byte[] bytes = Encoding.UTF8.GetBytes(inputString);
            byte[] hash = sha256.ComputeHash(bytes);
            return GetStringFromHash(hash);
        }
        private static string GetStringFromHash(byte[] hash)
        {
            StringBuilder result = new StringBuilder();
            for (int i = 0; i < hash.Length; i++)
            {
                result.Append(hash[i].ToString("X2"));
            }
            return result.ToString();
        }

        private readonly MovieRatingContext _context;

        public SecurityController(MovieRatingContext context)
        {
            _context = context;
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginInputModel inputModel)
        {

            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }
            bool authentic = await IsAuthenticAsync(inputModel.Username, inputModel.Password);
            if (!authentic)
            {
                ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                return View(inputModel);
            }

            // create claims
            List<Claim> claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, inputModel.Username),
            };

            // create identity
            ClaimsIdentity identity = new ClaimsIdentity(claims, "cookie");

            // create principal
            ClaimsPrincipal principal = new ClaimsPrincipal(identity);

            // sign-in
            await HttpContext.SignInAsync(
                    scheme: "MovieDatabase",
                    principal: principal);

            return RedirectToAction("Index", "Home");
        }
        public IActionResult Registration()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Registration(RegistrationInputModel inputModel)
        {
            if (_context.User.Any(u => u.Username == inputModel.Username))
                ModelState.AddModelError("Username ", "User name already exists. Please enter a different user name.");

            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }
            var passwordHash = GenerateSHA256String(inputModel.Password);
            _context.User.Add(new User { Username = inputModel.Username, Password = passwordHash, Email = inputModel.Email, Name = inputModel.Name});
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(
                    scheme: "MovieDatabase");

            return RedirectToAction("Login");
        }

        public IActionResult Access()
        {
            return View();
        }

        private async Task<bool> IsAuthenticAsync(string username, string password)
        {
            var user = await _context.User.SingleOrDefaultAsync(u => u.Username == username);
            if (user != null && user.Password == GenerateSHA256String(password))
            {
                return true;
            }
            return false;
        }
    }
}

Source/MovieRating/MovieRating.Web/Views/Security/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<form asp-controller="Security" asp-action="Login" method="post" class="form-signin">
    <input type="hidden" name="requestpath" id="requestpath" value="@ViewBag.RequestPath" />

    <h2 class="form-signin-heading">Please sign in</h2>

    <label for="username" class="sr-only">Username</label>
    <input type="text" id="username" name="username" class="form-control" placeholder="Username" required autofocus>

    <label for="password" class="sr-only">Password</label>
    <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>

    <div asp-validation-summary="All" class="text-danger"></div>

    <button class="btn btn-lg btn-primary btn-block" type="submit">
        Sign in
    </button>
    <a class="btn btn-lg btn-warning btn-block" asp-action="Registration" asp-route-returnurl="@ViewData["ReturnUrl"]">
        Register
    </a>
</form>

Source/MovieRating/MovieRating.Web/Views/Security/Registration.cshtml
@{
    ViewData["Title"] = "Registration";
}

<form asp-controller="Security" asp-action="Registration" method="post" class="form-register">
    <input type="hidden" name="requestpath" id="requestpath" value="@ViewBag.RequestPath" />

    <h2 class="form-signin-heading">Sign up for MovieRating!</h2>

    <label for="username" class="sr-only">Username</label>
    <input type="text" id="username" name="username" class="form-control" placeholder="Username" required autofocus />

    <label for="password" class="sr-only">Password</label>
    <input type="password" id="password" name="password" class="form-control" placeholder="Password" required />

    <label for="confirmpassword" class="sr-only">Confirm password:</label>
    <input type="password" name="confirmpassword" id="confirmpassword" class="form-control" placeholder="Confirm password" required />

    <label for="email" class="sr-only">Email</label>
    <input type="email" id="email" name="email" class="form-control" placeholder="Email" required />

    <label for="name" class="sr-only">Name</label>
    <input type="text" id="name" name="name" class="form-control" placeholder="Name" required />

    <div asp-validation-summary="All" class="text-danger"></div>

    <button class="btn btn-lg btn-warning btn-block" type="submit">
        Register
    </button>
</form>