Source/MovieRating/MovieRating.Web/Controllers/FriendsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieRating.DataAccess.Models.DB;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace MovieRating.Web.Controllers
{
    [Authorize]
    public class FriendsController : Controller
    {
        private readonly MovieRatingContext _context;

        public FriendsController(MovieRatingContext context)
        {
            _context = context;
        }

        // GET: Friends
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var currentUser = await GetCurrentUser();
            ViewData["currentUser"] = currentUser;

            var friends = _context.Friendship.Include(f => f.FriendUser).Include(f => f.User)
                .Where(f => f.UserId == currentUser.UserId).ToList();

            friends.AddRange(_context.Friendship.Include(f => f.FriendUser).Include(f => f.User)
                .Where(f => f.FriendId == currentUser.UserId));

            var otherUsers = await _context.User.Where(u => u.UserId != currentUser.UserId).Take(15).ToListAsync();

            return View(Tuple.Create(friends, otherUsers));
        }

        // GET: Friends/SendRequest/5
        [HttpGet]
        public async Task<IActionResult> SendRequest(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Friendship request = new Friendship
            {
                UserId = (await GetCurrentUser()).UserId,
                FriendId = id ?? 0,
                Status = 0
            };

            if (!_context.Friendship.Any(f => f.UserId == request.UserId && f.FriendId == id))
            { 
                _context.Friendship.Add(request);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Friends/AcceptRequest/5
        [HttpGet]
        public async Task<IActionResult> AcceptRequest(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User currentUser = await GetCurrentUser();

            Friendship request = await _context.Friendship
                .FirstOrDefaultAsync(f => f.UserId == id && f.FriendId == currentUser.UserId && f.Status == 0);

            if (request != null)
            {
                request.Status = 1;
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Friends/CancelRequest/5
        [HttpGet]
        public async Task<IActionResult> CancelRequest(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User currentUser = await GetCurrentUser();

            Friendship request = await _context.Friendship
                .FirstOrDefaultAsync(f => f.FriendId == id && f.UserId == currentUser.UserId && f.Status == 0);

            if (request != null)
            {
                _context.Friendship.Remove(request);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Friends/Unfriend/5
        [HttpGet]
        public async Task<IActionResult> Unfriend(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User currentUser = await GetCurrentUser();

            Friendship request = await _context.Friendship
                .FirstOrDefaultAsync(f => f.Status == 1 && 
                    (f.FriendId == id && f.UserId == currentUser.UserId || f.UserId == id && f.FriendId == currentUser.UserId));

            if (request != null)
            {
                _context.Friendship.Remove(request);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> FilterUser(string filter)
        {
            if (String.IsNullOrEmpty(filter))
            {
                return RedirectToAction(nameof(Index));
            }

            var currentUser = await GetCurrentUser();
            ViewData["currentUser"] = currentUser;

            List<Friendship> friends = _context.Friendship.Include(f => f.FriendUser).Include(f => f.User)
                .Where(f => f.UserId == currentUser.UserId).ToList();

            friends.AddRange(_context.Friendship.Include(f => f.FriendUser).Include(f => f.User)
                .Where(f => f.FriendId == currentUser.UserId));

            List<User> filteredUsers = 
                await _context.User.Where(u => u.UserId != currentUser.UserId &&
                                              (u.Username.Contains(filter) ||
                                               u.Email.Contains(filter) ||
                                               u.Name.Contains(filter))).ToListAsync();

            return View(nameof(Index), Tuple.Create(friends, filteredUsers));
        }

        virtual protected async Task<User> GetCurrentUser()
        {
            User currentUser = null;
            foreach (Claim claim in User.Claims.ToList())
            {
                if (claim.Type == ClaimTypes.Name)
                {
                    currentUser = await _context.User.FirstOrDefaultAsync(u => u.Username.Equals(claim.Value));
                }
            }
            return currentUser ?? new User();
        }
    }
}

Source/MovieRating/MovieRating.Web/Controllers/ProfilesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieRating.DataAccess.Models.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authentication;

namespace MovieRating.Web.Controllers
{
    [Authorize]
    public class ProfilesController : Controller
    {
        private readonly MovieRatingContext _context;

        public ProfilesController(MovieRatingContext context)
        {
            _context = context;
        }

        // GET: Profiles
        public async Task<ActionResult> Index()
        {
            var currentUser = await GetCurrentUser();
            ViewData["currentUser"] = currentUser;
            return View(currentUser);
        }

        // GET: Profiles/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentUser = await GetCurrentUser();
            ViewData["currentUser"] = currentUser;

            var areFriends = _context.Friendship.FirstOrDefault(f => 
                (f.UserId == currentUser.UserId && f.FriendId == id && f.Status == 1) ||
                (f.UserId == id && f.FriendId == currentUser.UserId && f.Status == 1)) != null;

            if (currentUser.UserId == id || !areFriends)
            {
                return RedirectToAction(nameof(Index));
            }

            var friendUser = await _context.User.Include(f => f.Userlist).FirstOrDefaultAsync(u => u.UserId == id);

            return View(nameof(Index), friendUser);
        }

        // GET: Profiles/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.Include(u => u.Usergroup).FirstOrDefaultAsync(u => u.UserId == id);

            if ((await GetCurrentUser()).UserId != id)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(user);
        }

        // POST: Profiles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int? id, [Bind("Username,Name,Email")] User user)
        {
            if (id == null || (await GetCurrentUser()).UserId != id)
            {
                return NotFound();
            }

            try
            {
                var userToModify = await _context.User.FirstOrDefaultAsync(u => u.UserId == id);

                if (user.Username != userToModify.Username && _context.User.Any(u => u.Username == user.Username))
                {
                    ModelState.AddModelError("UserName", "The username is already in use.");
                }

                if (String.IsNullOrWhiteSpace(user.Username))
                {
                    ModelState.AddModelError("UserName", "The username must not be empty.");
                }

                if (ModelState.IsValid)
                {
                    userToModify.Username = user.Username;
                    userToModify.Name = user.Name;
                    userToModify.Email = user.Email;

                    await _context.SaveChangesAsync();

                    if (userToModify.Username.Equals(user.Username))
                    {
                        await HttpContext.SignOutAsync(scheme: "MovieDatabase");
                        await SignInAsync(userToModify.Username);
                    }

                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        private async Task SignInAsync(string username)
        {
            // create claims
            List<Claim> claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, username),
            };

            // create identity
            ClaimsIdentity identity = new ClaimsIdentity(claims, "cookie");

            // create principal
            ClaimsPrincipal principal = new ClaimsPrincipal(identity);

            // sign-in
            await HttpContext.SignInAsync(
                    scheme: "MovieDatabase",
                    principal: principal);
        }

        virtual protected async Task<User> GetCurrentUser()
        {
            User currentUser = null;
            foreach (Claim claim in User.Claims.ToList())
            {
                if (claim.Type == ClaimTypes.Name)
                {
                    currentUser = await _context.User.Include(u => u.Userlist).FirstOrDefaultAsync(u => u.Username.Equals(claim.Value));
                }
            }
            return currentUser ?? new User();
        }
    }
}

Source/MovieRating/MovieRating.Web/Views/Friends/Index.cshtml
@model Tuple<List<MovieRating.DataAccess.Models.DB.Friendship>, List<MovieRating.DataAccess.Models.DB.User>>

@{
    ViewData["Title"] = "Friends";
}

<div class="container" style="width:600px">
    <h2>Friends</h2>
    <hr />

    @if (Model.Item1.Count == 0)
    {
        <div>You dont have any friends. Send someone a friend request below.</div>
    }
    else
    {
        <ul class="list-group">
            @foreach (var item in Model.Item1)
            {
                <li class="list-group-item" style="vertical-align:middle;line-height:35px">
                    @if (item.FriendId == (ViewData["currentUser"] as MovieRating.DataAccess.Models.DB.User).UserId)
                    {
                        @if (item.Status == 1)
                        {
                            <div style="float:left">
                                @Html.DisplayFor(modelItem => item.User.Name) (@Html.ActionLink(item.User.Username, "Details", "Profiles", new { id = item.UserId }, null))
                            </div>
                            <div style="float:right">
                                <a asp-action="Unfriend" asp-route-id="@item.UserId" class="btn btn-default btn-danger">Unfriend</a>
                            </div>
                        }
                        else
                        {
                            <div style="float:left">
                                @Html.DisplayFor(modelItem => item.User.Name) (@Html.DisplayFor(modelItem => item.User.Username))
                            </div>
                            <div style="float:right">
                                <a asp-action="AcceptRequest" asp-route-id="@item.UserId" class="btn btn-default btn-warning">Accept request</a>
                            </div>
                        }
                    }
                    else
                    {
                        @if (item.Status == 1)
                        {
                            <div style="float:left">
                                @Html.DisplayFor(modelItem => item.FriendUser.Name) (@Html.ActionLink(item.FriendUser.Username, "Details", "Profiles", new { id = item.FriendId }, null))
                            </div>
                            <div style="float:right">
                                <a asp-action="Unfriend" asp-route-id="@item.FriendId" class="btn btn-default btn-danger">Unfriend</a>
                            </div>
                        }
                        else
                        {
                            <div style="float:left">
                                @Html.DisplayFor(modelItem => item.FriendUser.Name) (@Html.DisplayFor(modelItem => item.FriendUser.Username))
                            </div>
                            <div style="float:right">
                                <a asp-action="CancelRequest" asp-route-id="@item.FriendId" class="btn btn-default btn-warning">Cancel request</a>
                            </div>
                        }
                    }
                    <div style="clear:both"></div>
                </li>
            }
        </ul>
    }

    <hr />
    <h2>Find new friends</h2>
    <form asp-action="FilterUser" method="get" class="form-horizontal" style="vertical-align:central">
        <div style="width:470px;float:left">
            <input name="filter" class="form-control" />
        </div>
        <div style="width:85px;float:right">
            <input type="submit" value="Filter" class="btn btn-default btn-primary" />
        </div>
        <div style="clear:both"></div>
    </form>
    <hr />

    <ul class="list-group">
        @foreach (var item in Model.Item2.Where(u => !Model.Item1.Any(f => f.FriendId == u.UserId || f.UserId == u.UserId)))
        {
            <li class="list-group-item" style="vertical-align:middle;line-height:35px">
                <div style="float:left">
                    @Html.DisplayFor(modelItem => item.Name) (@Html.DisplayFor(modelItem => item.Username))
                </div>
                <div style="float:right">
                    <a asp-action="SendRequest" asp-route-id="@item.UserId" class="btn btn-default btn-warning">Send friend request</a>
                </div>
                <div style="clear:both"></div>
            </li>
        }
    </ul>
</div>